name 'coralnexus-users'
version '0.4.0'

author 'Adrian Webb'
license 'ASL 2.0'
project_page 'http://github.com/coralnexus/puppet-users'
source 'git://github.com/coralnexus/puppet-users.git'
summary 'User management module'
description 'Configures user environments and manages users'
dependency 'coralnexus/corl', '>=0.4.0'
